### ISSUE TITLE
better UI messaging when access denied for user / password to db

### ISSUE THREAD

**Issue by jeffreyiacono** [tessro/oculus#10] opened 2012-06-13 17:57 UTC
right now, just displays "executing" and then the interface continues to poll the queries/{id}/status endpoint forever (figuratively speaking)

**Comment by tessro** [comment] 2012-06-13 20:09
I think this is a duplicate of #7

**Closed as completed** 2012-06-13 20:10 UTC

**Comment by jeffreyiacono** [comment] 2012-06-13 20:14
right you are
